name: Imprimir Detalles del Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  print-details:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout el repositorio
      uses: actions/checkout@v2
      
    - name: Obtener detalles del Pull Request
      run: |
        echo "Hello World"
        echo "Autor: ${{ github.event.pull_request.user.login }}"
        echo "Último Commit: ${{ github.event.pull_request.head.sha }}"
        git fetch origin ${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }}
        changes=$(git diff --name-only ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }})
        echo "Cambios entre el último commit y la rama principal:"
        echo "$changes"
