name: Hello World and Pull Request Details

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  hello_world_and_pull_request_details:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Hello World
        run: echo "Hello World"

      - name: Get Pull Request Details
        id: pr_details
        run: |
          echo "Author: ${{ github.event.pull_request.user.login }}"
          echo "Last Commit: ${{ github.event.pull_request.head.sha }}"
          echo "Changes:"
          git diff --name-status ${GITHUB_BASE_REF}...${GITHUB_HEAD_REF}

      - name: Display Pull Request Details
        run: |
          echo "Pull Request Details:"
          cat pr_details.txt

