name: First GitHub Action 

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  print_info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Pull Request Info
        run: |
          echo "Hello World"
          echo "Autor: ${{ github.event.pull_request.user.login }}"
          echo "Ultimo commit: ${{ github.event.pull_request.head.sha }}"
          echo "Cambios entre el último commit y el default branch:"
          git diff --name-only ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }}
