name: Hello World and PR Details

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  hello_world_and_pr_details:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Print Hello World
      run: echo "Hello World"
      
    - name: PR Details
      run: |
        echo "Author: ${{ github.event.pull_request.user.login }}"
        echo "Last Commit: ${{ github.event.pull_request.head.sha }}"
        echo "Changes between main and PR:"
        git diff --name-status main...${{ github.event.pull_request.head.ref }}
